### ISSUE TITLE
部署环境的时候打包失败

### ISSUE THREAD

**Issue by wanlongfei** [nxintech/job-center#1]
[root@VM_248_80_centos job-center-server]# gradle prod war
:job-center-server:prod FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':job-center-server:prod'.
  
  > A problem occurred starting process 'command '/usr/bin/gulp''
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.548 secs

**Comment by cjdxhjj** [comment]
首先应该安装一个node，建议安装node 5.7以上版本
